# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            Ash Kamel
tagline:          'Engineering Leader'
description:      'Engineering leader building teams and platforms at GitHub.'
url:              https://ashkamel.com
baseurl:          /
paginate:         5

author:
  name:           'Ash Kamel'
  url:            https://github.com/ajkamel

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ajkamel
