# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:
  - jekyll-paginate
  - pygments.rb
  - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            Ash Kamel
tagline:          '   Developer \ Tinkerer \ Referee'
description:      'Hi, welcome to my personal page, feel free to look around at some of my musings, portolio or interests.  If you would like to contact me please find my information below.'
url:              http://ashkamel.com
baseurl:          /
paginate:         5

author:
  name:           'Ash Kamel'
  url:            https://twitter.com/ajkamel

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ajkamel
